import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { AlertCircle, Upload, Send } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "../components/UI/Card";
import { Input, Textarea } from "../components/UI/Input";
import { Label } from "../components/UI/Label";
import { Button } from "../components/UI/Button";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "../components/UI/Select";
import { getApiUrl, API_ENDPOINTS } from "../lib/api";
import toast from "react-hot-toast";

type ComplaintForm = {
  name: string;
  email: string;
  contentUrl: string;
  contentType: "text" | "image" | "post" | "other";
  reason: "inaccurate" | "harmful" | "copyright" | "privacy" | "other";
  details: string;
  consent: boolean;
};

export default function ComplaintDeletion() {
  const navigate = useNavigate();
  const [submitting, setSubmitting] = useState(false);
  const [form, setForm] = useState<ComplaintForm>({
    name: "",
    email: "",
    contentUrl: "",
    contentType: "post",
    reason: "other",
    details: "",
    consent: false,
  });

  const update = <K extends keyof ComplaintForm>(key: K, value: ComplaintForm[K]) => {
    setForm(prev => ({ ...prev, [key]: value }));
  };

  const validate = () => {
    if (!form.name.trim()) return "Please provide your name.";
    if (!form.email.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) return "Please provide a valid email.";
    if (!form.details.trim() || form.details.trim().length < 20) return "Please describe the issue in at least 20 characters.";
    if (!form.consent) return "You must confirm the statement to proceed.";
    return null;
  };

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const error = validate();
    if (error) {
      toast.error(error);
      return;
    }
    setSubmitting(true);
    try {
      const resp = await fetch(getApiUrl(API_ENDPOINTS.DELETION_COMPLAINTS), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: form.name.trim(),
          email: form.email.trim(),
          content_url: form.contentUrl.trim() || null,
          content_type: form.contentType,
          reason: form.reason,
          details: form.details.trim(),
        })
      });
      const data = await resp.json().catch(() => ({}));
      if (!resp.ok) {
        throw new Error(data?.error || "Failed to submit complaint");
      }
      toast.success("Your complaint was submitted. We'll review it shortly.");
      navigate("/settings");
    } catch (err: any) {
      toast.error(err?.message || "Submission failed");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25 }}
      className="max-w-3xl mx-auto p-4 md:p-8"
    >
      <div className="mb-6">
        <h1 className="text-3xl font-semibold tracking-tight">Report or request deletion</h1>
        <p className="text-gray-500 dark:text-gray-400 mt-2">
          Use this form to report content generated by our website that you believe should be removed or corrected.
        </p>
      </div>

      <Card className="rounded-2xl shadow-sm">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <AlertCircle className="w-5 h-5" /> Content complaint form
          </CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={onSubmit} className="space-y-5">
            <div className="grid md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="name">Your name</Label>
                <Input id="name" value={form.name} onChange={e => update("name", e.target.value)} placeholder="Jane Doe" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" type="email" value={form.email} onChange={e => update("email", e.target.value)} placeholder="you@example.com" />
              </div>
            </div>

            <div className="grid md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="contentUrl">URL to the generated content (if available)</Label>
                <Input id="contentUrl" value={form.contentUrl} onChange={e => update("contentUrl", e.target.value)} placeholder="https://..." />
              </div>
              <div className="space-y-2">
                <Label>Content type</Label>
                <Select value={form.contentType} onValueChange={(v) => update("contentType", v as ComplaintForm["contentType"])}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select type" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="post">Post</SelectItem>
                    <SelectItem value="text">Text</SelectItem>
                    <SelectItem value="image">Image</SelectItem>
                    <SelectItem value="other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="grid md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Reason</Label>
                <Select value={form.reason} onValueChange={(v) => update("reason", v as ComplaintForm["reason"])}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select reason" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="inaccurate">Inaccurate or misleading</SelectItem>
                    <SelectItem value="harmful">Harmful or unsafe</SelectItem>
                    <SelectItem value="copyright">Copyright violation</SelectItem>
                    <SelectItem value="privacy">Privacy concern</SelectItem>
                    <SelectItem value="other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="details">Describe the issue</Label>
              <Textarea
                id="details"
                value={form.details}
                onChange={(e: any) => update("details", e.target.value)}
                placeholder="Provide as much context as possible..."
                className="min-h-[120px]"
              />
            </div>

            <div className="flex items-start gap-3">
              <input
                id="consent"
                type="checkbox"
                className="mt-1"
                checked={form.consent}
                onChange={(e) => update("consent", e.target.checked)}
              />
              <Label htmlFor="consent" className="text-sm text-gray-600 dark:text-gray-300">
                I confirm that the information provided is accurate to the best of my knowledge and I have the right to request review/removal of this content.
              </Label>
            </div>

            <div className="flex items-center gap-3">
              <Button type="submit" disabled={submitting} className="gap-2">
                <Send className="w-4 h-4" /> {submitting ? "Submitting..." : "Submit complaint"}
              </Button>
              <Button type="button" variant="outline" onClick={() => navigate(-1)}>
                Cancel
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>

      <div className="mt-6 text-xs text-gray-500 dark:text-gray-400">
        We review all reports and aim to respond promptly. If urgent, contact support via the email in our Privacy Policy.
      </div>
    </motion.div>
  );
}


